Repository nahyukk/Even-gram, pull requests merged in 2024-12, with the labels that each got.

#1 프로젝트 기본 세팅
  .gitignore
  assets/icons/dummy.png
  assets/images/dummy.png
  components/footer.html
  components/sidebar.html
  index.html
  js/footer.js
  js/index.js
  js/profile.js
  js/sidebar.js
  js/story.js
  profile.html
  story.html
  styles/footer.css
  styles/general.css
  styles/index.css
  styles/profile.css
  styles/sidebar.css
  styles/story.css
Labels: 📝 docs, 🌟 feat

#2 General.css 추가
  styles/general.css
Labels: 🎨 UI

#6 프로필 상단 UI추가
  assets/icons/setting.png
  assets/icons/thread.png
  profile.html
  styles/profile.css
Labels: 🎨 UI

#5 Feature/sidebar
  .vscode/settings.json
  assets/icons/active.png
  assets/icons/add.png
  assets/icons/back.png
  assets/icons/bookmark.png
  assets/icons/compass.png
  assets/icons/dark_active.png
  assets/icons/dark_add.png
  assets/icons/dark_back.png
  assets/icons/dark_bookmark.png
  assets/icons/dark_compass.png
  assets/icons/dark_dm.png
  assets/icons/dark_heart.png
  assets/icons/dark_home.png
  assets/icons/dark_insta.png
  assets/icons/dark_instalogo.png
  assets/icons/dark_menu.png
  assets/icons/dark_msg.png
  assets/icons/dark_profile.png
  assets/icons/dark_reels.png
  assets/icons/dark_search.png
  assets/icons/dark_setting.png
  assets/icons/dark_sun.png
  assets/icons/dark_threads.png
  assets/icons/dark_warning.png
  assets/icons/dm.png
  assets/icons/heart.png
  assets/icons/home.png
  assets/icons/insta-icon.png
  assets/icons/insta.png
  assets/icons/instalogo.png
  assets/icons/menu.png
  assets/icons/msg.png
  assets/icons/profile.png
  assets/icons/reels.png
  assets/icons/search.png
  assets/icons/setting.png
  assets/icons/sun.png
  assets/icons/threads.png
  assets/icons/warning.png
  assets/index.html
  assets/profile.html
  components/sidebar.html
  js/sidebar.js
  styles/sidebar.css
Labels: 🌟 feat, 🎨 UI

#4 Feature/story big UI
  assets/images/story_profile_jane.webp
  assets/images/story_profile_john.webp
  js/story.js
  json/stories.json
  story.html
  styles/story.css
Labels: 🎨 UI

#7 프로필 탭 섹션 추가
  assets/icons/profile_grid.png
  assets/icons/profile_reels.png
  assets/icons/profile_setting.png
  assets/icons/profile_tagged.png
  assets/icons/profile_thread.png
  profile.html
  styles/profile.css
Labels: 🎨 UI

#8 스토리 상단 버튼 기능 구현 및 스토리 외부 로고,x 버튼 ui, 기능 구현
  js/story.js
  story.html
  styles/story.css
Labels: 🌟 feat, 🎨 UI

#10 프로필 이미지 그리드 생성
  assets/icons/profile_post_comment.png
  assets/icons/profile_post_like.png
  assets/icons/profile_post_multiple.png
  js/profile.js
  json/profile.json
  profile.html
  styles/profile.css
Labels: 🎨 UI

#12 프로필 탭 클릭 액션
  assets/icons/profile_post_saved.png
  assets/icons/profile_reels.png
  js/profile.js
  json/profile.json
  profile.html
  styles/profile.css
Labels: 🌟 feat

#13 스토리 디엠 창 부분, 하트 버튼 기능 추가, 사이드 스토리 추가, <> 버튼 기능 추가
  assets/images/Instagram-Ring.png
  assets/images/Instagram_Stories_ring.svg
  index.html
  js/story.js
  json/stories.json
  story.html
  styles/story.css
Labels: 🐛 bug, 🌟 feat, 🎨 UI

#14 메인 푸터 작업 완료, 피드 기능 추가 및 변경, 버그 수정
  assets/icons/arrow.png
  assets/icons/bookmark.png
  assets/icons/bookmark_active.png
  assets/icons/bookmark_fill.png
  assets/icons/bookmark_fill_hover.png
  assets/icons/bookmark_hover.png
  assets/icons/dm.png
  assets/icons/dm_hover.png
  assets/icons/heart.png
  assets/icons/heart_active.png
  assets/icons/heart_fill.png
  assets/icons/heart_fill_active.png
  assets/icons/heart_hover.png
  assets/icons/more.png
  assets/icons/more_active.png
  assets/icons/msg.png
  assets/icons/msg_active.png
  assets/icons/msg_hover.png
  components/footer.html
  index.html
  js/index.js
  styles/footer.css
  styles/index.css
Labels: 🐛 bug, 🌟 feat, 🎨 UI

#15 스토리 dm 부분 버그 수정
  js/story.js
  story.html
Labels: 🐛 bug

#16 프로필 상단 미디어쿼리
  js/profile.js
  profile.html
  styles/profile.css
Labels: 🌟 feat

#17 스토리 미디어 쿼리 및 미트볼 버튼 모달 버그 수정
  js/story.js
  story.html
  styles/story.css
Labels: 🐛 bug, 🎨 UI

#20 프로필 하단 푸터 연결
  components/footer.html
  js/profile.js
  profile.html
  styles/profile.css
Labels: 🎨 UI

#21 홈 화면 스토리 UI 추가, 스토리 <>버튼기능 추가
  images
  index.html
  styles/index.css
Labels: 🌟 feat, 🎨 UI

#22 767px이하일 때 재생 버튼을 미트볼 버튼으로 변경
  js/story.js
  story.html
  styles/story.css
Labels: 🎨 UI

#25 sidebar 왼쪽 수정, 오른쪽 추가를 했습니다.
  assets/icons/active.png
  assets/icons/dark_active.png
  assets/icons/dark_threads.png
  assets/icons/threads.png
  assets/images/img1.jpg
  assets/images/img2.jpeg
  assets/images/img3.jpg
  assets/images/img4.jpg
  assets/images/img5.jpg
  assets/images/img6.jpg
  assets/index.html
  assets/profile.html
  components/sidebar.html
  index.html
  js/sidebar.js
  styles/index.css
  styles/sidebar.css
Labels: 🎨 UI

#24 스토리 사진 클릭시 양 옆 스토리 이동(767 이하) 및 스토리 작은 버그 수정
  js/story.js
  story.html
  styles/story.css
Labels: 🐛 bug, 🌟 feat

#23 프로필 아이콘 다크모드 적용
  assets/icons/profile_grid.png
  assets/icons/profile_post_saved.png
  assets/icons/profile_setting.png
  assets/icons/profile_tagged.png
  assets/icons/profile_thread.png
  profile.html
  styles/profile.css
Labels: 🎨 UI

#26 Feature/main
  assets/icons/dark_bookmark.png
  assets/icons/dark_bookmark_active.png
  assets/icons/dark_bookmark_fill.png
  assets/icons/dark_bookmark_fill_hover.png
  assets/icons/dark_bookmark_hover.png
  assets/icons/dark_dm.png
  assets/icons/dark_dm_hover.png
  assets/icons/dark_heart.png
  assets/icons/dark_heart_active.png
  assets/icons/dark_heart_fill_active.png
  assets/icons/dark_heart_hover.png
  assets/icons/dark_more.png
  assets/icons/dark_more_active.png
  assets/icons/dark_msg.png
  assets/icons/dark_msg_active.png
  assets/icons/dark_msg_hover.png
  index.html
  js/index.js
  json/feed.json
  styles/index.css
Labels: 🐛 bug, 🌟 feat, ♻️ refactor

#27 프로필 상단 미디어쿼리 수정
  styles/profile.css
Labels: 🐛 bug

#28 sidebar 수정 및 이동
  components/sidebar.html
  index.html
  js/sidebar.js
  styles/sidebar.css
Labels: 🌟 feat

#29 홈 화면 스토리 - 스토리 화면 연동
  index.html
  js/index.js
  js/story.js
  json/stories.json
  story.html
  styles/index.css
  styles/story.css
Labels: 🐛 bug, 🌟 feat

#32 메인 페이지 다크 모드 적용, 미디어 쿼리 적용
  assets/icons/dark_heart_fill_active.png
  styles/index.css
Labels: 🐛 bug, 🌟 feat

#31 작은 사이즈일 때 DM 입력 부분 스토리 사진 밖에 위치하도록 ui 수정
  styles/story.css
Labels: 🎨 UI

#33 검색탭 ui 작성
  index.html
  js/sidebar.js
  styles/sidebar.css
Labels: 🎨 UI

#34 검색 필터링 기능 구현, json 파일 추가
  index.html
  js/search.js
  json/search.json
  styles/sidebar.css
  styles/story.css
Labels: 🐛 bug, 🌟 feat

#36 랜덤 이미지 생성 로직 적용
  discovery.html
  js/discovery.js
  styles/discovery.css
Labels: 🎨 UI

#37 profile에 들어가는 사이드바 미디어쿼리 적용
  components/sidebar.html
  profile.html
  styles/sidebar.css
Labels: 🎨 UI

#38 검색 기능 및 ui 업그레이드!
  index.html
  js/search.js
  json/search.json
  styles/sidebar.css
Labels: 🌟 feat, ♻️ refactor, 🎨 UI

#39 검색 탭 ui 버그 수정
  js/search.js
  styles/index.css
  styles/sidebar.css
Labels: 🐛 bug

#40 탐색 무한 스크롤 구현
  js/discovery.js
  styles/discovery.css
Labels: 🎨 UI

#41 긴 이미지 추가
  assets/icons/profile_post_multiple.png
  js/discovery.js
  js/profile.js
  styles/discovery.css
  styles/profile.css
Labels: 🎨 UI

#42 검색탭 ui 수정 기능구현
  js/sidebar.js
  styles/sidebar.css
Labels: 🌟 feat

#44 검색 탭 버그 1차 수정 버전 입니다.
  js/sidebar.js
  styles/sidebar.css
Labels: 🐛 bug

#45 검색탭 2차 버그 수정
  assets/icons/search-x.png
  index.html
  js/search.js
  json/stories.json
  styles/sidebar.css
Labels: 🐛 bug, 🌟 feat, 🎨 UI

#46 피드 랜덤 생성, index.js 코드 최적화, 메인 페이지 가로 스크롤 등장 수정
  js/index.js
  styles/index.css
Labels: 🐛 bug, ♻️ refactor

#48 스토리 버그 수정
  js/story.js
  json/stories.json
  styles/story.css
Labels: 🐛 bug

#47 버튼 상태를 변경
  index.html
  js/index.js
Labels: 🌟 feat

#49 닫기 클릭 시 홈 화면 이동되도록 수정했습니다
  js/story.js
  story.html
  styles/story.css
Labels: 🌟 feat

#50 검색탭 3차 버그 수정
  js/search.js
  styles/sidebar.css
Labels: 🐛 bug

#52 스토리 부분 버그 수정
  js/index.js
  story.html
  styles/story.css
Labels: 🐛 bug, 🌟 feat

#51 홈화면 이외의 탭에서 사이드바 버튼 액션하도록 수정
  components/sidebar.html
  discovery.html
  index.html
  js/discovery.js
  js/index.js
  js/profile.js
  js/sidebar.js
  profile.html
Labels: 🐛 bug

#53 index.js 재수정과 피드 본문 놓친 부분 수정
  js/index.js
  styles/index.css
Labels: 🐛 bug

#54 사이드바 서치버튼 주석 해제
  js/sidebar.js
Labels: 🐛 bug

#56 V1.0.1 경로 문제 해결
  components/footer.html
  components/sidebar.html
  index.html
  js/discovery.js
  js/footer.js
  js/index.js
  js/profile.js
  js/search.js
  js/story.js
  json/search.json
  json/stories.json
Labels: 🐛 bug

#57 스토리 모달 버그 수정
  js/story.js
  styles/story.css
Labels: 🐛 bug

#58 v.1.0.2 배포 / main으로 머지 원합니다.
  js/story.js
  styles/story.css
Labels: 🔄 sync

#59 홈화면 외 다크모드 토글 활성화 및 로컬 스토리지에 테마 저장
  components/sidebar.html
  index.html
  js/darkModeManager.js
  js/discovery.js
  js/index.js
  js/profile.js
  js/sidebar.js
  styles/general.css
  styles/index.css
  styles/sidebar.css
Labels: 🐛 bug

#60 sync 1.0.3
  components/sidebar.html
  index.html
  js/darkModeManager.js
  js/discovery.js
  js/index.js
  js/profile.js
  js/sidebar.js
  styles/general.css
  styles/index.css
  styles/sidebar.css
Labels: 🔄 sync
